import { Component, OnInit, signal } from '@angular/core';
import { Product } from '../interfaces/product';
import { ProductService } from '../../shared/services/product.service';

@Component({
  selector: 'app-inventory',  // fixed selector typo
  templateUrl: './invertory.component.html',  // fixed filename typo if needed
  styleUrls: ['./invertory.component.scss'],  // fixed plural styleUrls
  standalone: false,
})
export class InventoryComponent implements OnInit {
  showModal = false;

  constructor(private productService: ProductService) {}

  page = signal<string>('Page 1 of 10');

  products: Product[] = [];
  newProduct: Product = {
    id: '',  // or omit if generated by backend
    name: '',
    category: '',
    price: 0,
    quantity: 0,
    unit: 0,
    exp_date: '',
    threshold: '',
  };

  ngOnInit(): void {
    this.productService.getProducts().subscribe((res: Product[]) => {
  this.products = res;
});

  }

  close() {
    if (this.showModal) {
      this.showModal = false;
    }
  }

  addProduct() {
    this.productService.addProduct(this.newProduct).subscribe({
      next: (res) => {
        console.log('Product added successfully', res);
        this.products.push(res);
        this.showModal = false;
      },
      error: (err) => console.error('Error adding product', err),
    });
  }
}
